// <auto-generated />
using System;
using AiAgents.BeeHiveAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiAgents.BeeHiveAgent.Infrastructure.Migrations
{
    [DbContext(typeof(BeeHiveAgentDbContext))]
    [Migration("20260107161337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiAgents.BeeHiveAgent.Domain.Entities.HiveImageSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HiveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ImageSamples");
                });

            modelBuilder.Entity("AiAgents.BeeHiveAgent.Domain.Entities.Prediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<Guid?>("HiveImageSampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PredictedLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HiveImageSampleId");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("AiAgents.BeeHiveAgent.Domain.Entities.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ActiveModelVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AutoThresholdHigh")
                        .HasColumnType("real");

                    b.Property<float>("AutoThresholdLow")
                        .HasColumnType("real");

                    b.Property<bool>("IsRetrainEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("NewGoldSinceLastTrain")
                        .HasColumnType("int");

                    b.Property<int>("RetrainGoldThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutoThresholdHigh = 0.9f,
                            AutoThresholdLow = 0.15f,
                            IsRetrainEnabled = true,
                            NewGoldSinceLastTrain = 0,
                            RetrainGoldThreshold = 50
                        });
                });

            modelBuilder.Entity("AiAgents.BeeHiveAgent.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("AiAgents.BeeHiveAgent.Domain.Entities.HiveImageSample", null)
                        .WithMany("Predictions")
                        .HasForeignKey("HiveImageSampleId");
                });

            modelBuilder.Entity("AiAgents.BeeHiveAgent.Domain.Entities.HiveImageSample", b =>
                {
                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
